### ISSUE TITLE
Version for orange pi zero 2w

### ISSUE THREAD

**Issue by Trimanat** [leeboby/kali-images#12]
I want to thank you for your work on images for other boards!
Can you please tell me if you can make a version for orange pi zero 2w 4Gb?
Thank you

**Comment by shut2005** [comment]
Yep)
please create image for orange pi zero 2w 4Gb)

I see way - install kali terminal and setup overhand of xcfe but, i think its no good idea

**Comment by leeboby** [comment]
Supported.
