### ISSUE TITLE
orangepi-config missing

### ISSUE THREAD

**Issue by philross88** [leeboby/kali-images#8]
I am trying to install it on the NVME and I see that orangepi-config is missing.

Is there any alternative?

我正在尝试将其安装在 NVME 上，但发现 Orangepi-config 丢失。

还有其他选择吗？

**Comment by hoshino114** [comment]
你可以使用其它orangepi的官方系统对spiflash刷入引导程序，然后可以直接将镜像刷入nvme（理论上应该可行，我没有试过）

**Comment by leeboby** [comment]
kali镜像没有orangepi-config。
