### ISSUE TITLE
Could someone create a 0 tutorial for the orange pi zero 3 4gb

### ISSUE THREAD

**Issue by Salvatore67678** [leeboby/kali-images#9]
I can't figure out what to do I need a step by step tutorial

**Comment by leeboby** [comment]
The latest image already supports 4GB.

**Comment by j0n777** [comment]
my zero 3 4gb can't boot, it shows error on mount

**Comment by j0n777** [comment]
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        14/07/2024     21:24     1572864000 kali-linux-2024.2-opizero3-xfce-arm64.img.xzaa
-a----        14/07/2024     21:44     1138865840 kali-linux-2024.2-opizero3-xfce-arm64.img.xzab
-a----        12/07/2024     21:58       12567188 win32diskimager-1.0.0-install.exe


PS D:\OrangePi> cat kali-linux-2024.2-opizero3-xfce-arm64.img.xza* > kali-linux-2024.2-opizero3-xfce-arm64.img.xz
PS D:\OrangePi> ls

tried to uncompress this file .xz with 7zip but fail
![1](https://github.com/user-attachments/assets/245587c8-fa35-4a7a-ab76-17ba9092b0f8)

and on balenaEtcher it shows this is not bootable img 
![2](https://github.com/user-attachments/assets/5a94415a-4a02-44be-848c-60d2f22563fb)
